src/com/linkedin/parseq/After.java, src/com/linkedin/parseq/BaseTask.java, src/com/linkedin/parseq/Tasks.java, src/com/linkedin/parseq/WithSideEffectTask.java, src/com/linkedin/parseq/internal/ContextImpl.java, test/com/linkedin/parseq/TestTasks.java, test/com/linkedin/parseq/trace/TestTaskToTrace.java
continuation of the RB we had that no longer works.  attempt to make the side effect not run if the parent task fails can be seen in WithSideEffectTask .run method.
=> Side effects

src/com/linkedin/parseq/Task.java
Saw revovery task name popping up in the parseq traces. Found that there is a typo in the naming of the task. Hence, fixing the typo in the name of the task.
=> Fixing typo in the name of the recovery task

contrib/parseq-zk-client/src/main/java/com/linkedin/parseq/zk/client/ZKClient.java, contrib/parseq-zk-client/src/main/java/com/linkedin/parseq/zk/recipes/MultiLocks.java, contrib/parseq-zk-client/src/main/java/com/linkedin/parseq/zk/recipes/Synchronizable.java, contrib/parseq-zk-client/src/main/java/com/linkedin/parseq/zk/recipes/ZKLock.java, contrib/parseq-zk-client/src/test/java/com/linkedin/parseq/zk/client/TestZKClient.java, contrib/parseq-zk-client/src/test/java/com/linkedin/parseq/zk/recipes/TestZKLock.java
This patch contains two improvements for parseq-zk-client.
1. Populate the path information from KeeperException thrown by #multi(Iterable)
2.  Add MultiLocks to zookeeper recipes
=> Two improvements for parseq-zk-client

src/com/linkedin/parseq/IndirectDelayedExecutor.java
Fixed bug in IndirectRunnable.cancel() method which returned true even if Runnable has run or has been cancelled.
=> Fixed bug in IndirectRunnable.cancel() method

src/com/linkedin/parseq/EngineBuilder.java
Make EngineBuilder#setPlanDeactivationListener backward compatible with v2.3.*
=> Make EngineBuilder#setPlanDeactivationListener backward compatible with v2.3.*

contrib/parseq-retry/src/main/java/com/linkedin/parseq/retry/RetriableTask.java, contrib/parseq-retry/src/test/java/com/linkedin/parseq/retry/TestRetriableTask.java
This is for developers' convenience - they don't have to take care of checked exceptions and leave error handling to ParSeq.
Unit test shows how function can throw a checked exception.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/linkedin/parseq/93)
=> Changed j.u.Function to c.l.p.f.Function1 that throws an Exception.

contrib/parseq-batching/src/test/java/com/linkedin/parseq/batching/TestSimpleBatchingStrategy.java, src/com/linkedin/parseq/internal/PlanContext.java
This PR should fix the issue #99
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/linkedin/parseq/100)
=> Make sub-PlanContext reuse the same plan id as its parent.

src/com/linkedin/parseq/Engine.java, src/com/linkedin/parseq/EngineBuilder.java, src/com/linkedin/parseq/Task.java, src/com/linkedin/parseq/TaskQueueFactory.java, src/com/linkedin/parseq/internal/FIFOPriorityQueue.java, src/com/linkedin/parseq/internal/PlanContext.java, src/com/linkedin/parseq/internal/PrioritizableRunnable.java, src/com/linkedin/parseq/internal/SerialExecutor.java, test/com/linkedin/parseq/internal/TestFIFOPriorityQueue.java, test/com/linkedin/parseq/internal/TestSerialExecutor.java
This patch should give us the ability to override the default FIFOPriorityQueue implementation in SerialExecutor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/linkedin/parseq/95)
=> Allow user to wire custom TaskQueue implementation into SerialExecutor

contrib/parseq-zk-client/src/main/java/com/linkedin/parseq/zk/client/ZKClient.java, contrib/parseq-zk-client/src/main/java/com/linkedin/parseq/zk/client/ZKClientBuilder.java, contrib/parseq-zk-client/src/main/java/com/linkedin/parseq/zk/client/ZKClientImpl.java, contrib/parseq-zk-client/src/test/java/com/linkedin/parseq/zk/client/TestZKClient.java, contrib/parseq-zk-client/src/test/java/com/linkedin/parseq/zk/recipes/TestZKLock.java
There are two benefits of this patch. First, it hides the implementation details to the user and makes it easier to extend in the future. Second, it enables decoration pattern around OS version of ZKClient so that we can, for example, save and restore execution context or add call tracking metrics and so forth.
=> Refactoring ZKClient to use interface + builder pattern

contrib/parseq-restli-client/src/main/java/com/linkedin/restli/client/GetRequestGroup.java, contrib/parseq-restli-client/src/main/java/com/linkedin/restli/client/ParSeqRestClient.java, contrib/parseq-restli-client/src/main/java/com/linkedin/restli/client/ParSeqRestliClientBuilder.java, contrib/parseq-restli-client/src/main/java/com/linkedin/restli/client/RequestGroup.java, contrib/parseq-restli-client/src/test/java/com/linkedin/restli/client/CapturingRestClient.java, contrib/parseq-restli-client/src/test/java/com/linkedin/restli/client/ParSeqRestClientIntegrationTest.java, contrib/parseq-restli-client/src/test/java/com/linkedin/restli/client/TestRequestContextProvider.java
RequestContext provider is a function that takes Request<?> object and
returns RequestContext object. It is used to create RequestContext
object in case when caller did not provide one as a parameter.
This change is backwards compatible. Up until now the implicit
RequestContext provider was: () -> new RequestContext() and it is now
explicit.
=> Added RequestContext provider to ParSeqRestClient.

CHANGELOG.md, contrib/parseq-batching/pom.xml, contrib/parseq-benchmark/pom.xml, contrib/parseq-examples/pom.xml, contrib/parseq-exec/pom.xml, contrib/parseq-http-client/pom.xml, contrib/parseq-legacy-examples/pom.xml, contrib/parseq-restli-client/pom.xml, contrib/parseq-restli-client/src/main/java/com/linkedin/restli/client/GetRequestGroup.java, contrib/parseq-tracevis-server/pom.xml, contrib/parseq-zk-client/pom.xml, version.properties
The change is primarily replacing:
Set<String> ids = rrbk.ids();
with:
Set<String> ids = (Set<String>) request.getObjectIds().stream()
.map(o -> BatchResponse.keyToString(o, version))
.collect(Collectors.toSet());
The second form handles complex keys correctly.
The rest of this change is refactoring of onSuccess() to split it into smaller methods.
=> Unbatch complex keys fix

CHANGELOG.md, src/com/linkedin/parseq/ParTaskImpl.java, src/com/linkedin/parseq/Task.java, src/com/linkedin/parseq/Tasks.java, test/com/linkedin/parseq/TestTaskFactoryMethods.java
Deprecate Tasks.par(...) for safer alternative Task.par(...) that does not throw IllegalArgumentException on empty collection.
=> Deprecate Tasks.par(...) for safer alternative Task.par(...) that does not throw IllegalArgumentException on empty collection.

CHANGELOG.md, src/com/linkedin/parseq/BaseTask.java, src/com/linkedin/parseq/ParSeqGlobalConfiguration.java, src/com/linkedin/parseq/ParTaskImpl.java, src/com/linkedin/parseq/Task.java, src/com/linkedin/parseq/Tasks.java, test/com/linkedin/parseq/TestTask.java, test/com/linkedin/parseq/TestTaskFactoryMethods.java
Normally tasks are executed in a different thread from the one creating it and at a different time. This makes it hard to debug because when a task throws an exception its call stack ends in the execution engine that actually starts a thread that serves the task. This feature collects task's stack trace in advance, when task is created, so that if the task throws the exception then the parent stack trace is appended to it. This has a small performance impact even if the task doesn't throw any exception because stack trace is collected in task constructor.
Stack trace before:
```
java.lang.RuntimeException: error
at com.linkedin.parseq.TestTask.lambda$getFailureTask$2(TestTask.java:135)
at com.linkedin.parseq.TestTask$$Lambda$91/209387180.call(Unknown Source)
at …
```
=> Enable automatic cross-thread stack tracing

CHANGELOG.md, src/com/linkedin/parseq/BaseTask.java
It turns out according to benchmarks that creating temporary exception object is approximately 10x faster than collecting the full stack trace by calling `Thread.getStackTrace()`. The reason is explained in https://stackoverflow.com/questions/26116181/access-stacktraces-with-good-performance - basically, collecting takes only 10% and the rest 90% is spent on converting it into a readable format. Since creating Throwable by itself doesn't do any conversion, it ends up being 10x faster.
=> Optimize task stack trace collection

contrib/parseq-restli-client/src/main/java/com/linkedin/restli/client/GetRequestGroup.java, contrib/parseq-restli-client/src/test/java/com/linkedin/restli/client/ParSeqRestClientBatchingIntegrationTest.java
Fix another projection building in doExecuteGet.
=> Use typesafe method to build projection.

tools/tracevis/lib/render/waterfall.js
According to the previous design of string truncation,  the length of the name string is less than 255 characters. 
Set the width of grid's right margin to a reasonable value instead of 250.
=> fix tracevis name truncation

build.xml, contrib/parseq-tracevis-server/pom.xml
Currently we build the parseq-tracevis-server-jar-with-dependencies.jar without version number. 
To make it easier to be managed and deployed, give version number to this jar.
=> add version number to tracevis server jar

CHANGELOG.md, fmpp/templates/com/linkedin/parseq/TupleNTask.java.ftl, src/com/linkedin/parseq/Tuple10Task.java, src/com/linkedin/parseq/Tuple11Task.java, src/com/linkedin/parseq/Tuple12Task.java, src/com/linkedin/parseq/Tuple13Task.java, src/com/linkedin/parseq/Tuple14Task.java, src/com/linkedin/parseq/Tuple15Task.java, src/com/linkedin/parseq/Tuple2Task.java, src/com/linkedin/parseq/Tuple3Task.java, src/com/linkedin/parseq/Tuple4Task.java, src/com/linkedin/parseq/Tuple5Task.java, src/com/linkedin/parseq/Tuple6Task.java, src/com/linkedin/parseq/Tuple7Task.java, src/com/linkedin/parseq/Tuple8Task.java, src/com/linkedin/parseq/Tuple9Task.java
Tuple*Task.java javadoc's image points to the image files which has a wrong file extension, which lead to the result that the .html file can not find the image files.
Update:
Since all the Tuple*Task.java source code are generated by freemarker template, we changed the template to set the right image extension, and then regenerate the source code.
=> fix Tuple*Task.java javadoc's image not showing bug

CHANGELOG.md, README.md, build.gradle, gradle.properties, subprojects/parseq-batching/README.md, subprojects/parseq-lambda-names/build.gradle, subprojects/parseq-restli-client/README.md, subprojects/parseq-tracevis/package.json, subprojects/parseq/build.gradle
Since parseq is migrated to Gradle, some link path in Readme file need to be updated. 
Also, parseq-tracevis has vulnerable dependencies issue, so upgrade the packages.
=> Update README file and fix vulnerable dependencies in package.json

CHANGELOG.md, subprojects/parseq-restli-client/src/main/java/com/linkedin/restli/client/GetRequestGroup.java, subprojects/parseq-restli-client/src/main/java/com/linkedin/restli/client/RestRequestBatchKey.java, subprojects/parseq-restli-client/src/test/java/com/linkedin/restli/client/ParSeqRestClientIntegrationTest.java, subprojects/parseq-restli-client/src/test/java/com/linkedin/restli/client/TestParSeqRestClient.java
Currently, ParSeq batch the get requests even the requests have different key type. This would get a 404 status when unbatch the response, since ParSeq always try to use the first request (use its type information) to send the batch request and unbatch response, this would cause this failure.
Update:
- This fix is to force the ParSeq only batch the requests with exactly the same key type.
- Fix the typo in RestRequestBatchKey class.
=> Make ParSeq batch get requests with exactly the same key type

CHANGELOG.md, build.gradle
Currently, the build.gradle file in the root project apply the "java plugin" to all sub modules, for the parseq-tracevis module(not a java project), it would generate the "publication" in the ivy.xml for the default parseq-tracevis.jar file automatically, which would lead to a wrong dependency import for other project.
Fix:
Exclude the "parseq-tracevis" module from "java plugin"
=> Fix parseq-tracevis.jar configuration bug

subprojects/parseq/src/main/java/com/linkedin/parseq/Task.java, subprojects/parseq/src/test/java/com/linkedin/parseq/AbstractTaskTest.java, subprojects/parseq/src/test/java/com/linkedin/parseq/internal/TestPlanCompletionListener.java
For #132 and #133 
Added support for  `static` `Task.withSideeffect` to replace using Parseq API for cases where other usages like `Task.value(null).withSideEffect(...)` were being used.
=> Add support for static withSideEffect

CHANGELOG.md, subprojects/parseq/src/main/java/com/linkedin/parseq/Task.java, subprojects/parseq/src/main/java/com/linkedin/parseq/TaskType.java, subprojects/parseq/src/main/java/com/linkedin/parseq/internal/ArgumentUtil.java, subprojects/parseq/src/test/java/com/linkedin/parseq/TestTaskType.java, subprojects/parseq/src/test/java/com/linkedin/parseq/TestTasks.java
Add support for Task.withDelay: #210 
This allows developers to delay a Task after a specified duration.
Also includes a new ArgumentUtil.requirePositive validation function that operates on long types.
=> Add support for Task.withDelay (#210)

CHANGELOG.md, gradle.properties, subprojects/parseq-tracevis-server/README.md, subprojects/parseq-tracevis-server/config.properties, subprojects/parseq-tracevis-server/src/main/java/com/linkedin/parseq/HealthCheckHandler.java, subprojects/parseq-tracevis-server/src/main/java/com/linkedin/parseq/TracevisHttpsServer.java, subprojects/parseq-tracevis-server/src/main/java/com/linkedin/parseq/TracevisServer.java, subprojects/parseq-tracevis-server/src/main/java/com/linkedin/parseq/TracevisServerJarMain.java
- Add https configuration support
- Add health check for tracevis server
It's a backward compatible change that you can either pass a http port number in command line to start a http server as previously described OR pass a configuration file path to start a https server.
=> Support HTTPS in parseq-tracevis-server

.travis.yml, CHANGELOG.md, subprojects/parseq-tracevis/README.md, subprojects/parseq/build.gradle
Use of http links will enable downloading of executable code over insecure channel. For safety reason, we change maven repo to use https link.
Other changes:
- Change travis configuration.
- Update parseq-tracevis README file.
=> Change maven repository link to https

subprojects/parseq-lambda-names/build.gradle, subprojects/parseq-lambda-names/src/main/java/com/linkedin/parseq/lambda/ASMBasedTaskDescriptor.java, subprojects/parseq-lambda-names/src/main/java/com/linkedin/parseq/lambda/Util.java, subprojects/parseq-lambda-names/src/test/java/com/linkedin/parseq/lambda/TestUtil.java
In HotSpot (java 8), the dynamic identifier for lambda expression like follows: 
HelloWorld$$Lambda$1 
In Zing (java 8):
HelloWorld$$Lambda$lambda$main$0$1310938867 
In parseq-lambda-names module, it uses a regular expression to filter the lambda function identifier. Since the lambda identifier in Zing can’t match the pattern("^.*\\$\\$Lambda\\$\\d+$"), it would fail to do the following work like, eg, to find the position of that lambda function in source code. 
So change the pattern to match the dynamic identifier in Zing.
=> Change Regex pattern to match the lambda function description in Zing

CHANGELOG.md, subprojects/parseq/src/main/java/com/linkedin/parseq/BaseTask.java, subprojects/parseq/src/test/java/com/linkedin/parseq/TestTasks.java
Fix for https://github.com/linkedin/parseq/issues/239
=> Guard exception thrown from tracing to avoid unfinished plan.

subprojects/parseq/src/test-utils/java/com/linkedin/parseq/ParSeqUnitTestHelper.java
The _taskDoneLatch map is ever growing as we keep running more and more tasks. If the CountDownLatch is 0, I think it means no one else is using it and so remove it from the map.
=> Making sure _taskDoneLatch doesn't keep growing

.travis.yml
Currently, feature branch PRs trigger two builds: one for the branch and one for the PR.
This attempts to remove that redundancy by only building on the master branch as well
as release tags.
=> Configure Travis to only build on master and tags

CHANGELOG.md, subprojects/parseq/build.gradle
Temporary fix to maintain compatibility with transitive consumers who
are still explicitly depending on the testArtifact configuration of
the parseq module. This simply tacks on the parseq-test-api dependency.
Steps to reproduce error:
1. Consumer A depends directly on `parseq-test-api@4.0.0`
2. Consumer B depends directly on Consumer A, yet also depends directly on `parseq@3.*` using the `testArtifact` configuration.
3. Consumer B's dependency on `parseq` will be bumped up to `4.0.0`, which will cause an error because the `testArtifact` configuration doesn't exist for `parseq@4.0.0`.
Without this fix, transitive consumers of parseq 4.0.0 may still be explicitly depending on the `testArtifact` configuration of the `parseq` module, which would result in an error like this:
```
Could not …
```
=> Add testArtifact configuration back

CHANGELOG.md, build.gradle, gradle.properties, gradle/bintray.gradle, gradle/maven.gradle, scripts/local-release, scripts/release, subprojects/parseq-batching/build.gradle, subprojects/parseq-benchmark/build.gradle, subprojects/parseq-examples/build.gradle, subprojects/parseq-exec/build.gradle, subprojects/parseq-http-client/build.gradle, subprojects/parseq-lambda-names/build.gradle, subprojects/parseq-legacy-examples/build.gradle, subprojects/parseq-restli-client/build.gradle, subprojects/parseq-test-api/build.gradle, subprojects/parseq-tracevis-server/build.gradle, subprojects/parseq-tracevis/build.gradle, subprojects/parseq-zk-client/build.gradle, subprojects/parseq/build.gradle
Removes the old `MavenDeployer` setup, adds a new OSS
publishing mechanism using the Bintray Gradle plugin,
with the top-level publishing task being `bintrayUpload`.
Adds the `local-release` script which publishes Maven
artifacts to `~/local-release.
**NOTE:** Build failing because of nodejs.org server errors, going to force re-build tomorrow.
=> Configure bintrayUpload task, add local-release script

CHANGELOG.md, build.gradle, gradle.properties, gradle/bintray.gradle, gradle/maven.gradle, scripts/local-release, scripts/release, subprojects/parseq-batching/build.gradle, subprojects/parseq-benchmark/build.gradle, subprojects/parseq-examples/build.gradle, subprojects/parseq-exec/build.gradle, subprojects/parseq-http-client/build.gradle, subprojects/parseq-lambda-names/build.gradle, subprojects/parseq-legacy-examples/build.gradle, subprojects/parseq-restli-client/build.gradle, subprojects/parseq-test-api/build.gradle, subprojects/parseq-tracevis-server/build.gradle, subprojects/parseq-tracevis/build.gradle, subprojects/parseq-zk-client/build.gradle, subprojects/parseq/build.gradle
**Note:** Duplicate of #243, just applying this change after the 4.0.1 release.
Removes the old MavenDeployer setup, adds a new OSS publishing mechanism
using the Bintray Gradle plugin, with the top-level publishing task
being 'bintrayUpload'. Adds the 'local-release' script which publishes
Maven artifacts to '~/local-release'.
=> Configure bintrayUpload, add local-release script

CHANGELOG.md, gradle.properties
Reasoning for bumping the minor version: the changes to the Gradle build scripts and the way we publish artifacts have been dramatically altered. Although I have shown that the published archives will be compatible, I'm bumping the minor version to be safe as per semver.
=> Prep v4.1.0 release.

subprojects/parseq-tracevis/package.json
Upgrading phantomjs to solve one of the build issue in testCov, fails on mac only since c++ libs used to build are different on mac. Other issues relating to installation failure:
Root cause is contextify being no longer support as it is merged native to node. 
Permanent fix is upgrade node and package dependencies. 
for now will have use below patches(one time). I will add specific cmds to developer guide.
Refer:
https://github.com/nodejs/node-gyp/issues/569
https://github.com/nodejs/node-gyp/issues/469
=> fix mac build issue for tracevis

.travis.yml, build.gradle, scripts/help-text/local-release.txt, scripts/help-text/release.txt, scripts/local-release, scripts/release, scripts/travis/publish-tag.sh, subprojects/parseq-benchmark/build.gradle, subprojects/parseq-tracevis-server/build.gradle
Sets up automatic Bintray publications in Travis whenever a tag is pushed. Improves the `local-release` script and re-purposes the `release` script to create and push a tag to trigger a deployment. Also removes the "Built-By" property from the JAR manifest.
**Release Workflow:**
1. `./scripts/release` to release from the current HEAD.
2. Go to ParSeq on GitHub to verify that the publication job ran successfully.
**Snapshot Workflow:**
- `./scripts/local-release` to publish `x.y.z` to `~/local-repo`
- `./scripts/local-release -s` to publish `x.y.z-SNAPSHOT` to `~/local-repo`
**Note:**
- I did some mocked testing of the `publish-tag.sh` Travis script, but I can't do an end-to-end test until this is merged.
- Both scripts (`release` and `local-release`) support the `-h, --help` argument, so …
=> Set up automated releases, improve helper scripts

.travis.yml, scripts/travis/publish-tag.sh
Previously removed the tags from the build condition, but turns out that actually removes it from the deploy condition as well.
Will attempt to release `4.1.1` from this commit.
=> Include tags in Travis build, set env variables

scripts/travis/publish-tag.sh
Iterative fix for the Travis release automation. Since Travis checks out the repo from the release tag, we need to fetch master in order to determine if the release tag is an ancestor of master.
=> Fetch master in the Travis publish-tag script

.travis.yml
Iterative fix for the Travis release automation. The Bintray upload failed because the build step was building snapshot artifacts, whereas the upload task was looking for release artifats. This should correct that.
=> Build non-snapshot artifacts in Travis

CHANGELOG.md, gradle.properties, subprojects/parseq-restli-client/src/main/java/com/linkedin/restli/client/ParSeqRestClient.java, subprojects/parseq-restli-client/src/test/java/com/linkedin/restli/client/TestParSeqRestClientClientException.java
Currently, if the Client implementation throws an uncaught exception, the callback isn't executed. This is to ensure the Task is always failed if the Client implementation throws an exception.
=> Wrapping Client request in try catch to propagate failure to Task

subprojects/parseq/src/main/java/com/linkedin/parseq/Task.java, subprojects/parseq/src/test/java/com/linkedin/parseq/TestTasks.java
This adds a `fromTry` static method to the `Task` class which captures the success and failure semantics of `Try` expressing them as a `Task`.
Closes #274
=> Introduce Task::fromTry factory method

scripts/travis/publish-tag.sh
There exists a problem now where a Bintray upload can partially fail,
leaving the repo in a bad state where future uploads may fail due to
conflicts. This fix adjusts the Travis script so that a failed Bintray
upload will result in an API call to completely delete the version.
Same as the fix made in Rest.li: https://github.com/linkedin/rest.li/pull/318
=> Roll back Bintray upload on failure in Travis

CHANGELOG.md, gradle.properties, settings.gradle, subprojects/parseq-all/build.gradle
Adds a new module, `parseq-all`, which is simply a meta-project that
programmatically depends on all other consumer-facing modules. This
makes it easier for certain use cases to pull in the entire dependency
tree.
=> Introduce parseq-all meta-project

CHANGELOG.md, subprojects/parseq-restli-client/src/main/java/com/linkedin/restli/client/GetRequestGroup.java, subprojects/parseq-restli-client/src/main/java/com/linkedin/restli/client/RequestGroup.java
Currently, the GetRequestGroup implementation leaves out cookies while batching requests. This causes issues, especially for batched requests to frontends which may use cookies for authentication logic.
Likely the assumption was the cookies were included in the headers, but unfortunately they are not in the R2 Request object.
This change might be backwards incompatible for some requests. It will not change the ability for requests to be batched, because currently the key in the map uses the whole request object to check for equality, so it is already checking for cookie equality. However we aren't currently sending the cookies with the batch-get request, so if that could transform the response, then this would be backwards incompatible.
=> Adding cookies to the generated request from GetRequestGroup

subprojects/parseq/src/main/java/com/linkedin/parseq/Task.java
Reworded the javadoc for Task methods so failure handling for timeout task will be clearer.
In short
- Timeout task will be considered failure and will be handled by failure handling methods
- Cancelled task will not be considered as failure for failure handling methods
- Initiating task chain with timeout methods will return a "withtimeout" subtask. When the "withtimeout" subtask timeout, the subtask is not cancelled, but the initiating task is cancelled (this brought some confusion in the doc)
=> Reword javadoc in Task for .recover() and .withTimeout()

CHANGELOG.md, subprojects/parseq/src/main/java/com/linkedin/parseq/Task.java
Before, there were multiple javadoc warnings coming from `Task.java`:
```
> Task :parseq:javadoc
/..../parseq/subprojects/parseq/src/main/java/com/linkedin/parseq/Task.java:283: warning - invalid usage of tag >
/..../parseq/subprojects/parseq/src/main/java/com/linkedin/parseq/Task.java:284: warning - invalid usage of tag >
/..../parseq/subprojects/parseq/src/main/java/com/linkedin/parseq/Task.java:355: warning - invalid usage of tag >
/..../parseq/subprojects/parseq/src/main/java/com/linkedin/parseq/Task.java:356: warning - invalid usage of tag >
......
......
/..../parseq/subprojects/parseq/src/main/java/com/linkedin/parseq/Task.java:488: warning - invalid usage of tag <
/..../parseq/subprojects/parseq/src/main/java/com/linkedin/parseq/Task.java:488: warning - invalid usage of tag >
66 …
```
=> Fix for multiple javadoc warnings coming from Task.java

CHANGELOG.md, subprojects/parseq/src/main/java/com/linkedin/parseq/Task.java, subprojects/parseq/src/test/java/com/linkedin/parseq/AbstractTaskTest.java, subprojects/parseq/src/test/java/com/linkedin/parseq/TestFusionTask.java, subprojects/parseq/src/test/java/com/linkedin/parseq/TestTask.java
From my experience, it's a repeating pattern to provide different recovery for different types of failures. Currently, it looks like this:
```
Task<Response> task = createResponseTask().recover(ex -> {
if (failure instanceof BadRequestException) {
return new Response(HTTP_400, ex.getMessage());
}
else if (failure instanceof AuthException) {
return new Response(HTTP_403, ex.getMessage());
}
else if (failure instanceof ServiceException) {
return new Response(HTTP_500, ex.getMessage());
});
```
With this introduction of 'recover with failure filter' this same code would get shorter and more concise:
```
Task<Response> task = createResponseTask()
.recover(BadRequestException.class, ex -> new Response(HTTP_400, ex.getMessage()))
.recover(AuthException.class, ex -> new Response(HTTP_403, …
```
=> Adding Task.recover(String, Class<X extends Throwable>, func) method

gradle.properties, subprojects/parseq-tracevis-server/src/main/java/com/linkedin/parseq/TracevisServerJarMain.java
A minor fix for TracevisServer:
The stack trace was previously missing
=> Add stack trace in error message when starting TracevisServer

.gitignore, CHANGELOG.md, gradle.properties, subprojects/parseq-guava-interop/src/main/java/com/linkedin/parseq/guava/ListenableFutureUtil.java
This change is created out of an investigation for following stacktrace when ParSeq is used together with grpc-java
```
com.linkedin.parseq.promise.PromiseResolvedException: <LOG MESSAGE REDACTED DUE TO LINKEDIN'S PRIVACY POLICY>
at com.linkedin.parseq.promise.SettablePromiseImpl.ensureNotDone(SettablePromiseImpl.java:156)
at com.linkedin.parseq.promise.SettablePromiseImpl.finalizeResult(SettablePromiseImpl.java:124)
at com.linkedin.parseq.promise.SettablePromiseImpl.doFinish(SettablePromiseImpl.java:116)
at com.linkedin.parseq.promise.SettablePromiseImpl.fail(SettablePromiseImpl.java:56)
at com.linkedin.parseq.BaseTask.fail(BaseTask.java:336)
at com.linkedin.parseq.BaseTask.lambda$contextRun$0(BaseTask.java:207)
at com.linkedin.parseq.promise.SettablePromiseImpl.notifyListener(SettablePro …
```
=> To prevent ListenableFutureUtil throw PromiseAlreadyResolved exception, also added log to see why it happened

.github/workflows/build.yml, .github/workflows/publish.yml
https://github.com/linkedin/parseq/issues/318
=> Use a pined jdk 8 version in github action,as a workaround for issue #318

CHANGELOG.md, gradle.properties, subprojects/parseq-guava-interop/build.gradle, subprojects/parseq-guava-interop/src/main/java/com/linkedin/parseq/guava/ListenableFutureUtil.java, subprojects/parseq-guava-interop/src/test/java/com/linkedin/parseq/guava/ListenableFutureUtilTest.java
Based on following stack trace
```
2022/01/14 13:50:52.897 [[31merror[0m] [c.l.p.p.SettablePromiseImpl] [grpc-default-executor-461] [voyager-api-notifications] [] An exception was thrown by listener
com.linkedin.parseq.promise.PromiseResolvedException: Promise has already been satisfied
at com.linkedin.parseq.promise.SettablePromiseImpl.ensureNotDone(SettablePromiseImpl.java:156)
at com.linkedin.parseq.promise.SettablePromiseImpl.finalizeResult(SettablePromiseImpl.java:124)
at com.linkedin.parseq.promise.SettablePromiseImpl.doFinish(SettablePromiseImpl.java:116)
at com.linkedin.parseq.promise.SettablePromiseImpl.done(SettablePromiseImpl.java:51)
at com.linkedin.parseq.BaseTask.done(BaseTask.java:322)
at com.linkedin.parseq.BaseTask.lambda$contextRun$0(BaseTask.java:209)
at …
```
=> Fix promiseAlreadyResolved exception thrown by ListenableFutureUtil

CHANGELOG.md, subprojects/parseq-lambda-names/src/main/java/com/linkedin/parseq/lambda/LambdaMethodVisitor.java, subprojects/parseq-lambda-names/src/main/java/com/linkedin/parseq/lambda/SourcePointer.java
Customer complains about NPE thrown and printed at 
https://github.com/linkedin/parseq/blob/master/subprojects/parseq-lambda-names/src/main/java/com/linkedin/parseq/lambda/ASMBasedTaskDescriptor.java#L219
Some of them were confused and thought they were actual errors.
The cause of these NPE are also not clear. Adding message can help us understand why it happens in some code.
Here mute the message and print more meaningful warning.
=> Mute an NPE thrown by parseq-lambda-names

CHANGELOG.md, gradle.properties, subprojects/parseq-lambda-names/src/main/java/com/linkedin/parseq/lambda/ASMBasedTaskDescriptor.java, subprojects/parseq-lambda-names/src/main/java/com/linkedin/parseq/lambda/LambdaClassLocator.java
User reporting the threads hang when waiting for coundown latch in AsmBasedTaskDescriptor
It is not obvious why it will hang, a guess is that some lambda functions are being evaluated multiple times.
This changes it to add more print information to locate those lambda function
=> add more print information to instrument the occasional lambda name generation failure during boot time

.github/workflows/build.yml, CHANGELOG.md, gradle.properties, subprojects/parseq-guava-interop/src/main/java/com/linkedin/parseq/guava/ListenableFutureUtil.java
Previous implementation has two problems that fixed in this PR.
1. We now use best effort to cancel GRPC future and that shouldn't impact the return value of `cancelled()` that supposed to indicate base Task cancellation 
2. We should  only cancel GRPC future when base task state transition confirmed to happen.
=> Fix cancel() implementation in ListanbleFutureUtil

.github/workflows/publish.yml, CHANGELOG.md, gradle.properties
Have to pin the python version since new version doesn't work with node-gyp
=> Pin python version in the publish github action

.gitignore, CHANGELOG.md, gradle.properties, subprojects/parseq-restli-client/src/main/java/com/linkedin/restli/client/DirectExecutor.java, subprojects/parseq-restli-client/src/main/java/com/linkedin/restli/client/ParSeqRestClient.java, subprojects/parseq-restli-client/src/main/java/com/linkedin/restli/client/ParSeqRestliClientBuilder.java, subprojects/parseq/src/main/java/com/linkedin/parseq/FusionTask.java
This PR adds the option to run sendRequest in a dedicated threadpool.
Although sendRequest is asynchronous, we found that it may still block the scheduling thread for extended amount of time in certain scenarios.
Here is one example we had in production:
With this change, we no longer have such blocking behavior in the scheduling thread.
=> run sendRequest in an executor

CHANGELOG.md, gradle.properties
Release of UI changes from https://github.com/linkedin/parseq/pull/342.
=> Release 5.1.18 with trace visualizer updates

subprojects/parseq/src/main/java/com/linkedin/parseq/ParTaskImpl.java, subprojects/parseq/src/test/java/com/linkedin/parseq/TestParTask.java
The `tasksFromIterable` method in `ParTaskImpl` needs to read the contents of an iterator and then create an array of the read tasks. This is an unfortunate performance/memory tradeoff of using these two things: iterators don't have a length and arrays need one. The implementation reads the iterator's contents into a collection and then turns that collection into an array. The problem is, it then tries to cast that array of `Object` into a more narrow type, which is not allowed. This _always_ results in a ClassCastException if the value is non null. The exists tests did not cover this case.
The code has been fixed to take a less performant path and delegate the array creation to `tasksFromCollection`. A test has been written for the `Iterable` code path and verified through coverage …
=> Fix broken implementation of ParTaskImpl::tasksFromIterable

CHANGELOG.md, gradle.properties, subprojects/parseq-lambda-names/src/main/java/com/linkedin/parseq/lambda/SourcePointer.java, subprojects/parseq/src/main/java/com/linkedin/parseq/trace/ShallowTraceBuilder.java
There has been a report that some race condition can cause `resultType` being referenced as required constructor argument from a builder (during trace build) before it is being set.
StackTrace is as below:
```
java.lang.NullPointerException: resultType must not be null"java.lang.NullPointerException: resultType must not be null
at com.linkedin.parseq.internal.ArgumentUtil.requireNotNull(ArgumentUtil.java:28)
at com.linkedin.parseq.trace.ShallowTraceImp.<init>(ShallowTraceImp.java:52)
at com.linkedin.parseq.trace.ShallowTraceBuilder.build(ShallowTraceBuilder.java:304)
at com.linkedin.parseq.trace.TraceBuilder.lambda$build$1(TraceBuilder.java:85)
at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
at com.linkedin.parseq.trace.TraceBuilder.build(TraceBuilder.java:85)
at …
```
=> Explicitly set default value to "UNFINISHED" for TraceBuilder's ResultType

.github/scripts/build.sh, subprojects/parseq/src/test/java/com/linkedin/parseq/AbstractTaskTest.java
Test failures in github action: https://github.com/linkedin/parseq/actions/runs/16303725941/job/46050223728 
The current test `testStaticWithSideEffectFullCompletion` assert that the task is not done immediately after invoking `run`:
```
Task<Void> sideEffect = Task.withSideEffect(() -> slowSideEffect);
run(sideEffect);
assertFalse(sideEffect.isDone());
```
However, this may not be true in all environments and looks like in github action the task can be completed faster.
Removing the assertion to make the test stable in github action.
=> Fix flaky test testStaticWithSideEffectFullCompletion
