linkedin/parseq

.gitignore

Without this: 
```bash
$ cd contrib/parseq-examples/
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
$ mvn clean install
...
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
(use "git add <file>..." to include in what will be committed)
target/
nothing added to commit but untracked files present (use "git add" to track)
```

Ignore maven target folder

---

contrib/parseq-examples/pom.xml

Fix TraceUtil compilation pr…oblems
Fix maven encoding warning

parseq-examples: bump parseq to 2.0.2

---

contrib/parseq-tracevis-server/src/main/java/com/linkedin/parseq/Constants.java
contrib/parseq-tracevis-server/src/main/java/com/linkedin/parseq/GraphvizEngine.java
contrib/parseq-tracevis-server/src/main/java/com/linkedin/parseq/GraphvizResponse.java
contrib/parseq-tracevis-server/src/main/java/com/linkedin/parseq/TracevisServer.java
tools/tracevis/lib/render/graphviz.js

- Fix bug: svg acted incorrect when html has base tag
- Fix bug: POST to dot required application/json, replace with text/plain
- Fix bug: minus sign was covered
- Fix typos
- Generalize TracevisServer into a separate GraphvisEngine which can be used by any web server framework, e.g. jetty or play

Fix TracevisServer:

---

CHANGELOG.md
contrib/parseq-benchmark/pom.xml
contrib/parseq-examples/pom.xml
contrib/parseq-examples/src/main/java/com/linkedin/parseq/example/composite/MergeSortExample.java
contrib/parseq-exec/pom.xml
contrib/parseq-http-client/pom.xml
contrib/parseq-legacy-examples/pom.xml
contrib/parseq-tracevis-server/pom.xml
src-test/com/linkedin/parseq/BaseEngineTest.java
src/com/linkedin/parseq/BaseTask.java
src/com/linkedin/parseq/FusionTask.java
src/com/linkedin/parseq/FusionTraceContext.java
src/com/linkedin/parseq/ParTaskImpl.java
src/com/linkedin/parseq/Task.java
test/com/linkedin/parseq/TestFusionTask.java
test/com/linkedin/parseq/TestParTask.java
test/com/linkedin/parseq/TestTask.java
test/com/linkedin/parseq/TestTaskFactoryMethods.java
test/com/linkedin/parseq/TestTaskReuse.java
test/com/linkedin/parseq/TestTaskStates.java
test/com/linkedin/parseq/trace/TestFusionTaskTrace.java
test/com/linkedin/parseq/trace/TestTaskToTrace.java
version.properties

Tracing improvements:
- Changed the way tasks fusion is reflected in trace so that it is  more intuitive and better reflect performance of individual transformations
- Added class name of lambdas passed to functional API to default task descriptions

Trace improvements

---

src/com/linkedin/parseq/internal/Continuations.java

Follow up on https://github.com/linkedin/parseq/pull/66

Simplify Continuations.

---

src-test/com/linkedin/parseq/BaseEngineTest.java

Added trace logging to runAndWaitException.
Added variations of runAndWaitException.

Cleaned up BaseEngineTest

---

contrib/parseq-zk-client/src/test/java/com/linkedin/parseq/zk/client/TestZKClient.java
contrib/parseq-zk-client/src/test/resources/log4j.properties

Fix a bug in TestZKClient where we didn't wait for the zookeeper connection to be established completely.

Fix a bug in TestZKClient

---

src/com/linkedin/parseq/promise/SettablePromiseImpl.java

Fixing typo in SettablePromiseImpl

---

tools/tracevis/index.js
tools/tracevis/lib/trace/criticalPath.js
tools/tracevis/lib/trace/exclude.js
tools/tracevis/test/unit/criticalPath-test.js
tools/tracevis/trace.html

Critical path computation and filtering for tracevis

Critical path computation and filtering for tracevis

---

src/com/linkedin/parseq/After.java
src/com/linkedin/parseq/BaseTask.java
src/com/linkedin/parseq/EngineBuilder.java
src/com/linkedin/parseq/EngineImpl.java
src/com/linkedin/parseq/Task.java
src/com/linkedin/parseq/internal/ContextImpl.java
src/com/linkedin/parseq/internal/PlanCompletionListener.java
src/com/linkedin/parseq/internal/PlanContext.java

Adding PlanCompletionListener which gets invoked when all the tasks(including sideEffect task) start by this plan have been finished.

Adding PlanCompletionListener

---

src/com/linkedin/parseq/internal/PlanContext.java
test/com/linkedin/parseq/internal/TestPlanCompletionListener.java

Add unit test for PlanCompletionListener.

Add unit test for PlanCompletionListener

---

src-test/com/linkedin/parseq/BaseEngineTest.java
src/com/linkedin/parseq/Engine.java
src/com/linkedin/parseq/EngineBuilder.java
test/com/linkedin/parseq/TestEngine.java
test/com/linkedin/parseq/internal/TestPlanCompletionListener.java

Implement _taskDoneListener using PlanCompletionListener to take sideEffect task into account.

Implement _taskDoneListener using PlanCompletionListener

---

CHANGELOG.md
contrib/parseq-batching/pom.xml
contrib/parseq-benchmark/pom.xml
contrib/parseq-examples/pom.xml
contrib/parseq-exec/pom.xml
contrib/parseq-http-client/pom.xml
contrib/parseq-legacy-examples/pom.xml
contrib/parseq-restli-client/pom.xml
contrib/parseq-tracevis-server/pom.xml
contrib/parseq-zk-client/pom.xml
src/com/linkedin/parseq/Engine.java
test/com/linkedin/parseq/TestEngineConcurrentPlans.java
version.properties

Engine.run(...) methods are blocking now when the max concurrent plans limit is reached. For backwards compatibility default value for this limit is Integer.MAX_VALUE, what essentially means "unbounded capacity".
Added non blocking and time-bounded blocking tryRun(...) methods.

Added limit on max concurrent plans to be executed by the Engine

---

src/com/linkedin/parseq/Engine.java
test/com/linkedin/parseq/TestEngineConcurrentPlans.java

Changed behavior of Engine.run() to not block but throw an
IllegalStateException once Engine's capacity has been exceeded.
Some ParSeq users follow an anti-pattern of not building plans by
composition but instead are executing new plans using Engine.run() even
from within another task. Changing semantics to blocking would cause
unrecoverable deadlock. It is better to throw an exception in this case
because it can/should be handled by code that executes Engine.run().

Changed behavior of Engine.run() to not block but throw an IllegalStateException

---

contrib/parseq-restli-client/src/test/java/com/linkedin/restli/client/TestRequestContextProvider.java

The problem was some tests which were borrowed from TestParseqRestClient were not clearing contexts. Looks like these tests are already part of TestParSeqRestClient so removing them.

fixing test in TestRequestContextProvider. 

---

CHANGELOG.md
build.gradle
gradle.properties
subprojects/parseq-lambda-names/build.gradle
subprojects/parseq/build.gradle

Set up testNG in build.gradle to do unit test and change the test configuration in parseq-lambda-names module.

Configure unit test in Gradle

---

subprojects/parseq/src/main/java/com/linkedin/parseq/Engine.java
subprojects/parseq/src/main/java/com/linkedin/parseq/EngineBuilder.java
subprojects/parseq/src/main/java/com/linkedin/parseq/internal/DefaultPlanBasedRateLimiter.java
subprojects/parseq/src/main/java/com/linkedin/parseq/internal/PlanBasedRateLimiter.java
subprojects/parseq/src/test/java/com/linkedin/parseq/TestEnginePlanBasedRateLimit.java

This PR supports max concurrency plan configured based on plan class.

Support plan based rate limiting.

---

subprojects/parseq/build.gradle
subprojects/parseq/src/test-utils/java/com/linkedin/parseq/BaseEngineTest.java
subprojects/parseq/src/test-utils/java/com/linkedin/parseq/ParSeqUnitTestHelper.java
subprojects/parseq/src/test-utils/java/com/linkedin/parseq/junitjupiter/BaseEngineJUnitJupiterTest.java
subprojects/parseq/src/test-utils/java/com/linkedin/parseq/junitjupiter/BaseEngineParJunitJupiterTest.java
subprojects/parseq/src/test/java/com/linkedin/parseq/ParSeqUnitTestHelperTest.java

- avoided couplings with TestNG
- introduced base classes to be used by JUnit5 customers
This implementation was pair-programmed with Jiaqi Guan

Enabled test utility for JUnit5

---

subprojects/parseq-benchmark/src/main/java/com/linkedin/parseq/EventsArrival.java
subprojects/parseq-restli-client/src/main/java/com/linkedin/restli/client/ParSeqRestClient.java
subprojects/parseq-zk-client/src/main/java/com/linkedin/parseq/zk/client/ZKClient.java
subprojects/parseq/src/main/java/com/linkedin/parseq/Engine.java
subprojects/parseq/src/main/java/com/linkedin/parseq/Task.java
subprojects/parseq/src/main/java/com/linkedin/parseq/internal/Clock.java
subprojects/parseq/src/main/java/com/linkedin/parseq/internal/PlanDeactivationListener.java
subprojects/parseq/src/main/java/com/linkedin/parseq/internal/PlatformClock.java
subprojects/parseq/src/main/java/com/linkedin/parseq/internal/SystemHiddenTask.java

See all the warnings here
https://scans.gradle.com/s/n3ap5h46hu6ne/console-log#L84

Fixed 19 build time warnings

---

CHANGELOG.md
gradle.properties

Using this to test the automated release system.

Prep v4.1.1 release.

---

.travis.yml

Iterative fix for the Travis release workflow.

Prevent Travis from cleaning up build artifacts

---

CHANGELOG.md
gradle.properties
subprojects/parseq-benchmark/src/main/java/com/linkedin/parseq/AbstractBenchmark.java
subprojects/parseq/src/main/java/com/linkedin/parseq/BaseTask.java
subprojects/parseq/src/main/java/com/linkedin/parseq/FusionTask.java
subprojects/parseq/src/main/java/com/linkedin/parseq/internal/TaskLogger.java
subprojects/parseq/src/main/java/com/linkedin/parseq/trace/ShallowTrace.java
subprojects/parseq/src/main/java/com/linkedin/parseq/trace/ShallowTraceBuilder.java
subprojects/parseq/src/main/java/com/linkedin/parseq/trace/ShallowTraceImp.java
subprojects/parseq/src/main/java/com/linkedin/parseq/trace/Trace.java
subprojects/parseq/src/main/java/com/linkedin/parseq/trace/TraceBuilder.java
subprojects/parseq/src/main/java/com/linkedin/parseq/trace/TraceRelationship.java
subprojects/parseq/src/main/java/com/linkedin/parseq/trace/codec/json/JsonTraceDeserializer.java
subprojects/parseq/src/main/java/com/linkedin/parseq/trace/codec/json/JsonTraceSerializer.java
subprojects/parseq/src/test/java/com/linkedin/parseq/TestTaskStates.java
subprojects/parseq/src/test/java/com/linkedin/parseq/trace/TestShallowTraceBuilder.java
subprojects/parseq/src/test/java/com/linkedin/parseq/trace/TestTaskToTrace.java
subprojects/parseq/src/test/java/com/linkedin/parseq/trace/TestTraceBuilder.java
subprojects/parseq/src/test/java/com/linkedin/parseq/trace/codec/json/TestJsonTraceCodec.java

Solves https://github.com/linkedin/parseq/issues/244

use native long instead of Long wrapper for ShallowTrace

---

gradle.properties

This is just make the change in gradle.properties.

Bump the version in gradle.properties

---

.travis.yml

Encrypt JFrog credentials for travis-ci.com

---

subprojects/parseq/build.gradle
subprojects/parseq/src/main/java/com/linkedin/parseq/retry/RetryPolicy.java
subprojects/parseq/src/main/java/com/linkedin/parseq/retry/termination/GuavaRateLimiter.java
subprojects/parseq/src/main/java/com/linkedin/parseq/retry/termination/LimitRate.java
subprojects/parseq/src/main/java/com/linkedin/parseq/retry/termination/RateLimiter.java
subprojects/parseq/src/main/java/com/linkedin/parseq/retry/termination/RequireAny.java
subprojects/parseq/src/main/java/com/linkedin/parseq/retry/termination/TerminationPolicy.java
subprojects/parseq/src/test/java/com/linkedin/parseq/retry/TestRetryPolicy.java
subprojects/parseq/src/test/java/com/linkedin/parseq/retry/TestTerminationPolicy.java

I added a RateLimit retry policy to help with controlling the qps of retries.

Add rate limit retry policy

---

CHANGELOG.md
gradle.properties

Per customer request, release 5.1.5

Release 5.1.5

---

.github/scripts/publish.sh

Also port over fix from Rest.li making non-master publish error messages
more clear and actionable.

Fix CI publish script's tag validation

---

.github/workflows/build.yml
.github/workflows/publish.yml
build.gradle

Update actions/setup-java version to v4 to fix cache service issue (Error: Cache service responded with 400) ref:https://github.com/linkedin/parseq/actions/runs/15898775597/job/45673060370?pr=352

Update actions/setup-java version to v4 to fix cache service issue.
